[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pad = {git = "https://github.com/Warhorst/pad.git"}
rayon = "1.8.0"
num = "0.4.1"
polygonical = "0.5.0"